/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TrustHowItWorksRouteImport } from './routes/trust/how-it-works'
import { Route as MeDonationsRouteImport } from './routes/me/donations'
import { Route as DashboardVerificationsRouteImport } from './routes/dashboard/verifications'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPayoutsRouteImport } from './routes/dashboard/payouts'
import { Route as DashboardEvidenceRouteImport } from './routes/dashboard/evidence'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard/campaigns'
import { Route as AdminVerificationsRouteImport } from './routes/admin/verifications'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRecipientsRouteImport } from './routes/admin/recipients'
import { Route as AdminEvidenceRouteImport } from './routes/admin/evidence'
import { Route as RRecipientSlugIndexRouteImport } from './routes/r/$recipientSlug/index'
import { Route as CCampaignSlugIndexRouteImport } from './routes/c/$campaignSlug/index'
import { Route as DonateCampaignSlugConfirmRouteImport } from './routes/donate/$campaignSlug/confirm'
import { Route as ApiImgIdRouteImport } from './routes/api/img/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOgCampaignCampaignSlugRouteImport } from './routes/api/og/campaign/$campaignSlug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrustHowItWorksRoute = TrustHowItWorksRouteImport.update({
  id: '/trust/how-it-works',
  path: '/trust/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MeDonationsRoute = MeDonationsRouteImport.update({
  id: '/me/donations',
  path: '/me/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVerificationsRoute = DashboardVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayoutsRoute = DashboardPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvidenceRoute = DashboardEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipientsRoute = AdminRecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvidenceRoute = AdminEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AdminRoute,
} as any)
const RRecipientSlugIndexRoute = RRecipientSlugIndexRouteImport.update({
  id: '/r/$recipientSlug/',
  path: '/r/$recipientSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCampaignSlugIndexRoute = CCampaignSlugIndexRouteImport.update({
  id: '/c/$campaignSlug/',
  path: '/c/$campaignSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateCampaignSlugConfirmRoute =
  DonateCampaignSlugConfirmRouteImport.update({
    id: '/donate/$campaignSlug/confirm',
    path: '/donate/$campaignSlug/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiImgIdRoute = ApiImgIdRouteImport.update({
  id: '/api/img/$id',
  path: '/api/img/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCampaignCampaignSlugRoute =
  ApiOgCampaignCampaignSlugRouteImport.update({
    id: '/api/og/campaign/$campaignSlug',
    path: '/api/og/campaign/$campaignSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/evidence': typeof AdminEvidenceRoute
  '/admin/recipients': typeof AdminRecipientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/verifications': typeof DashboardVerificationsRoute
  '/me/donations': typeof MeDonationsRoute
  '/trust/how-it-works': typeof TrustHowItWorksRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/img/$id': typeof ApiImgIdRoute
  '/donate/$campaignSlug/confirm': typeof DonateCampaignSlugConfirmRoute
  '/c/$campaignSlug/': typeof CCampaignSlugIndexRoute
  '/r/$recipientSlug/': typeof RRecipientSlugIndexRoute
  '/api/og/campaign/$campaignSlug': typeof ApiOgCampaignCampaignSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/evidence': typeof AdminEvidenceRoute
  '/admin/recipients': typeof AdminRecipientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/verifications': typeof DashboardVerificationsRoute
  '/me/donations': typeof MeDonationsRoute
  '/trust/how-it-works': typeof TrustHowItWorksRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/img/$id': typeof ApiImgIdRoute
  '/donate/$campaignSlug/confirm': typeof DonateCampaignSlugConfirmRoute
  '/c/$campaignSlug': typeof CCampaignSlugIndexRoute
  '/r/$recipientSlug': typeof RRecipientSlugIndexRoute
  '/api/og/campaign/$campaignSlug': typeof ApiOgCampaignCampaignSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/evidence': typeof AdminEvidenceRoute
  '/admin/recipients': typeof AdminRecipientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/evidence': typeof DashboardEvidenceRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/verifications': typeof DashboardVerificationsRoute
  '/me/donations': typeof MeDonationsRoute
  '/trust/how-it-works': typeof TrustHowItWorksRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/img/$id': typeof ApiImgIdRoute
  '/donate/$campaignSlug/confirm': typeof DonateCampaignSlugConfirmRoute
  '/c/$campaignSlug/': typeof CCampaignSlugIndexRoute
  '/r/$recipientSlug/': typeof RRecipientSlugIndexRoute
  '/api/og/campaign/$campaignSlug': typeof ApiOgCampaignCampaignSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/register'
    | '/admin/evidence'
    | '/admin/recipients'
    | '/admin/reports'
    | '/admin/verifications'
    | '/dashboard/campaigns'
    | '/dashboard/evidence'
    | '/dashboard/payouts'
    | '/dashboard/profile'
    | '/dashboard/verifications'
    | '/me/donations'
    | '/trust/how-it-works'
    | '/admin/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/img/$id'
    | '/donate/$campaignSlug/confirm'
    | '/c/$campaignSlug/'
    | '/r/$recipientSlug/'
    | '/api/og/campaign/$campaignSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/register'
    | '/admin/evidence'
    | '/admin/recipients'
    | '/admin/reports'
    | '/admin/verifications'
    | '/dashboard/campaigns'
    | '/dashboard/evidence'
    | '/dashboard/payouts'
    | '/dashboard/profile'
    | '/dashboard/verifications'
    | '/me/donations'
    | '/trust/how-it-works'
    | '/admin'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/img/$id'
    | '/donate/$campaignSlug/confirm'
    | '/c/$campaignSlug'
    | '/r/$recipientSlug'
    | '/api/og/campaign/$campaignSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/register'
    | '/admin/evidence'
    | '/admin/recipients'
    | '/admin/reports'
    | '/admin/verifications'
    | '/dashboard/campaigns'
    | '/dashboard/evidence'
    | '/dashboard/payouts'
    | '/dashboard/profile'
    | '/dashboard/verifications'
    | '/me/donations'
    | '/trust/how-it-works'
    | '/admin/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/img/$id'
    | '/donate/$campaignSlug/confirm'
    | '/c/$campaignSlug/'
    | '/r/$recipientSlug/'
    | '/api/og/campaign/$campaignSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  MeDonationsRoute: typeof MeDonationsRoute
  TrustHowItWorksRoute: typeof TrustHowItWorksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImgIdRoute: typeof ApiImgIdRoute
  DonateCampaignSlugConfirmRoute: typeof DonateCampaignSlugConfirmRoute
  CCampaignSlugIndexRoute: typeof CCampaignSlugIndexRoute
  RRecipientSlugIndexRoute: typeof RRecipientSlugIndexRoute
  ApiOgCampaignCampaignSlugRoute: typeof ApiOgCampaignCampaignSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trust/how-it-works': {
      id: '/trust/how-it-works'
      path: '/trust/how-it-works'
      fullPath: '/trust/how-it-works'
      preLoaderRoute: typeof TrustHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/donations': {
      id: '/me/donations'
      path: '/me/donations'
      fullPath: '/me/donations'
      preLoaderRoute: typeof MeDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verifications': {
      id: '/dashboard/verifications'
      path: '/verifications'
      fullPath: '/dashboard/verifications'
      preLoaderRoute: typeof DashboardVerificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payouts': {
      id: '/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof DashboardPayoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/evidence': {
      id: '/dashboard/evidence'
      path: '/evidence'
      fullPath: '/dashboard/evidence'
      preLoaderRoute: typeof DashboardEvidenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipients': {
      id: '/admin/recipients'
      path: '/recipients'
      fullPath: '/admin/recipients'
      preLoaderRoute: typeof AdminRecipientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evidence': {
      id: '/admin/evidence'
      path: '/evidence'
      fullPath: '/admin/evidence'
      preLoaderRoute: typeof AdminEvidenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$recipientSlug/': {
      id: '/r/$recipientSlug/'
      path: '/r/$recipientSlug'
      fullPath: '/r/$recipientSlug/'
      preLoaderRoute: typeof RRecipientSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$campaignSlug/': {
      id: '/c/$campaignSlug/'
      path: '/c/$campaignSlug'
      fullPath: '/c/$campaignSlug/'
      preLoaderRoute: typeof CCampaignSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/$campaignSlug/confirm': {
      id: '/donate/$campaignSlug/confirm'
      path: '/donate/$campaignSlug/confirm'
      fullPath: '/donate/$campaignSlug/confirm'
      preLoaderRoute: typeof DonateCampaignSlugConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img/$id': {
      id: '/api/img/$id'
      path: '/api/img/$id'
      fullPath: '/api/img/$id'
      preLoaderRoute: typeof ApiImgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/campaign/$campaignSlug': {
      id: '/api/og/campaign/$campaignSlug'
      path: '/api/og/campaign/$campaignSlug'
      fullPath: '/api/og/campaign/$campaignSlug'
      preLoaderRoute: typeof ApiOgCampaignCampaignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEvidenceRoute: typeof AdminEvidenceRoute
  AdminRecipientsRoute: typeof AdminRecipientsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEvidenceRoute: AdminEvidenceRoute,
  AdminRecipientsRoute: AdminRecipientsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardEvidenceRoute: typeof DashboardEvidenceRoute
  DashboardPayoutsRoute: typeof DashboardPayoutsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardVerificationsRoute: typeof DashboardVerificationsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardEvidenceRoute: DashboardEvidenceRoute,
  DashboardPayoutsRoute: DashboardPayoutsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardVerificationsRoute: DashboardVerificationsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  MeDonationsRoute: MeDonationsRoute,
  TrustHowItWorksRoute: TrustHowItWorksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImgIdRoute: ApiImgIdRoute,
  DonateCampaignSlugConfirmRoute: DonateCampaignSlugConfirmRoute,
  CCampaignSlugIndexRoute: CCampaignSlugIndexRoute,
  RRecipientSlugIndexRoute: RRecipientSlugIndexRoute,
  ApiOgCampaignCampaignSlugRoute: ApiOgCampaignCampaignSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
